<?php

function creativecommons_get_license_from_url($url) {

$lic_traditionalcopyright = unserialize('O:23:"creativecommons_license":6:{s:11:"license_uri";N;s:12:"license_name";N;s:12:"license_type";s:20:"traditionalcopyright";s:11:"permissions";a:3:{s:8:"requires";a:0:{}s:9:"prohibits";a:0:{}s:7:"permits";a:0:{}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";}');

$lic_publicdomain = unserialize('O:23:"creativecommons_license":7:{s:11:"license_uri";s:49:"http://creativecommons.org/licenses/publicdomain/";s:12:"license_name";s:13:"Public Domain";s:12:"license_type";s:12:"publicdomain";s:11:"permissions";a:3:{s:8:"requires";a:0:{}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";i:2;s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}}');

$lic_cc_by_nc_sa = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:49:"http://creativecommons.org/licenses/by-nc-sa/2.0/";s:12:"license_name";s:40:"Attribution-NonCommercial-ShareAlike 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:3:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";i:2;s:37:"http://web.resource.org/cc/ShareAlike";}s:9:"prohibits";a:1:{i:0;s:40:"http://web.resource.org/cc/CommercialUse";}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"n";s:11:"derivatives";s:2:"sa";s:12:"jurisdiction";s:0:"";}');

$lic_cc_by = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:43:"http://creativecommons.org/licenses/by/2.0/";s:12:"license_name";s:15:"Attribution 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"y";s:11:"derivatives";s:1:"y";s:12:"jurisdiction";s:0:"";}');

$lic_cc_by_nd = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:46:"http://creativecommons.org/licenses/by-nd/2.0/";s:12:"license_name";s:24:"Attribution-NoDerivs 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:0:{}s:7:"permits";a:2:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"y";s:11:"derivatives";s:1:"n";s:12:"jurisdiction";s:0:"";}');

$lic_cc_by_nc = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:46:"http://creativecommons.org/licenses/by-nc/2.0/";s:12:"license_name";s:29:"Attribution-NonCommercial 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:1:{i:0;s:40:"http://web.resource.org/cc/CommercialUse";}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"n";s:11:"derivatives";s:1:"y";s:12:"jurisdiction";s:0:"";}');

$lic_cc_by_nc_nd = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:49:"http://creativecommons.org/licenses/by-nc-nd/2.0/";s:12:"license_name";s:38:"Attribution-NonCommercial-NoDerivs 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:1:{i:0;s:40:"http://web.resource.org/cc/CommercialUse";}s:7:"permits";a:2:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"n";s:11:"derivatives";s:1:"n";s:12:"jurisdiction";s:0:"";}');

$lic_cc_by_sa = unserialize('O:23:"creativecommons_license":10:{s:11:"license_uri";s:46:"http://creativecommons.org/licenses/by-sa/2.0/";s:12:"license_name";s:26:"Attribution-ShareAlike 2.0";s:12:"license_type";s:8:"standard";s:11:"permissions";a:3:{s:8:"requires";a:3:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";i:2;s:37:"http://web.resource.org/cc/ShareAlike";}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:10:"commercial";s:1:"y";s:11:"derivatives";s:2:"sa";s:12:"jurisdiction";s:0:"";}');

$lic_cc_sampling = unserialize('O:23:"creativecommons_license":9:{s:11:"license_uri";s:49:"http://creativecommons.org/licenses/sampling/1.0/";s:12:"license_name";s:12:"Sampling 1.0";s:12:"license_type";s:7:"recombo";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:0:{}s:7:"permits";a:2:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:12:"jurisdiction";s:0:"";s:8:"sampling";s:8:"sampling";}');

$lic_cc_samplingplus = unserialize('O:23:"creativecommons_license":9:{s:11:"license_uri";s:50:"http://creativecommons.org/licenses/sampling+/1.0/";s:12:"license_name";s:17:"Sampling Plus 1.0";s:12:"license_type";s:7:"recombo";s:11:"permissions";a:3:{s:8:"requires";a:2:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:34:"http://web.resource.org/cc/Sharing";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:12:"jurisdiction";s:0:"";s:8:"sampling";s:12:"samplingplus";}');

$lic_cc_nc_samplingplus = unserialize('O:23:"creativecommons_license":9:{s:11:"license_uri";s:53:"http://creativecommons.org/licenses/nc-sampling+/1.0/";s:12:"license_name";s:32:"NonCommericial Sampling Plus 1.0";s:12:"license_type";s:7:"recombo";s:11:"permissions";a:3:{s:8:"requires";a:3:{i:0;s:33:"http://web.resource.org/cc/Notice";i:1;s:38:"http://web.resource.org/cc/Attribution";i:2;s:37:"http://web.resource.org/cc/ShareAlike";}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";a:7:{s:6:"format";s:5:"other";s:5:"title";s:0:"";s:11:"description";s:0:"";s:7:"creator";s:0:"";s:6:"rights";s:0:"";s:4:"date";s:0:"";s:6:"source";s:0:"";}s:3:"nid";s:1:"4";s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}s:12:"jurisdiction";s:0:"";s:8:"sampling";s:14:"ncsamplingplus";}');

$lic_gpl = unserialize('O:23:"creativecommons_license":7:{s:11:"license_uri";s:44:"http://creativecommons.org/licenses/GPL/2.0/";s:12:"license_name";s:26:"GNU General Public License";s:12:"license_type";s:3:"gpl";s:11:"permissions";a:3:{s:8:"requires";a:1:{i:0;s:33:"http://web.resource.org/cc/Notice";}s:9:"prohibits";a:0:{}s:7:"permits";a:3:{i:0;s:39:"http://web.resource.org/cc/Reproduction";i:1;s:39:"http://web.resource.org/cc/Distribution";i:2;s:42:"http://web.resource.org/cc/DerivativeWorks";}}s:8:"metadata";N;s:3:"nid";i:7397;s:3:"rdf";a:1:{s:10:"attributes";a:3:{s:9:"xmlns:rdf";s:43:"http://www.w3.org/1999/02/22-rdf-syntax-ns#";s:5:"xmlns";s:27:"http://web.resource.org/cc/";s:8:"xmlns:dc";s:32:"http://purl.org/dc/elements/1.1/";}}}');

  switch ($url) {
    case "http://creativecommons.org/licenses/publicdomain/":
        return $lic_publicdomain;
    case "http://creativecommons.org/licenses/by-nc-sa/2.0/":
        return $lic_cc_by_nc_sa;
    case "http://creativecommons.org/licenses/by/2.0/":
        return $lic_cc_by;
    case "http://creativecommons.org/licenses/by-nd/2.0/":
        return $lic_cc_by_nd;
    case "http://creativecommons.org/licenses/by-nc-nd/2.0/":
        return $lic_cc_by_nc_nd;
    case "http://creativecommons.org/licenses/by-sa/2.0/":
        return $lic_cc_by_sa;
    case "http://creativecommons.org/licenses/sampling/1.0/":
        return $lic_cc_sampling;
    case "http://creativecommons.org/licenses/sampling+/1.0/":
        return $lic_cc_samplingplus;
    case "http://creativecommons.org/licenses/nc-sampling+/1.0/":
        return $lic_cc_nc_samplingplus;
    case "http://creativecommons.org/licenses/GPL/2.0/":
        return $lic_gpl;
    default:
        return $lic_traditionalcopyright;
  }
}
?>
