<?php
/**
 * Implementation of hook_help().
 */
function userposts_help($section) {
  if ($section == 'admin/modules#description') {
     return t('Show a user summary page.');
  }
}

/**
 * Implementation of hook_menu().
 */
function userposts_menu() {
  $items[] = array('path' => 'profile/page', 'title' => t('profile page'),
    'callback' => 'profile_page',
    'access' => TRUE,
    'type' => MENU_SUGGESTED_ITEM);
  
  return $items;
}

/**
 * Menu callback; display a user page.
 */
function userposts_user($op, &$edit, &$user, $category = NULL) {
  if($op == 'view') {
    foreach (node_list() as $type) {
      $listres = db_query('SELECT n.nid, n.title, n.type FROM {node} n WHERE n.uid=%d AND n.type = \'%s\' ORDER BY n.changed DESC LIMIT %d',$user->uid, $type, variable_get('profile_list_amount', 10));
      while ($row = db_fetch_object($listres)) {
        $items[] = l($row->title, 'node/'.$row->nid);
      }
      if (strstr($type, 'flexinode')) {
        $type = flexinode_node_name($type);
      }
      $items ? $output .= theme('item_list',$items,t('%user\'s %type posts',array('%user' => $user->name, '%type'=>$type))) : NULL;
      $items= array();
    }   
    return $output ? array(t('User posts') => $output) : "";
  }
}

/**
 * Helper functions. 
 */
/*
 *Prepares a list of titles
 */
function _userposts_title_list($result, $title="NULL") {
  while ($row = db_fetch_object($result)) {
    $nids[] = $row->nid;
  }
  if(!$nids) {
    return;
  }
  
  foreach(node_list() as $type) {
    foreach($nids as $nid) {
      if($node = node_load(array('nid'=>$nid,'type'=>$type))) {
        $items[] = l($node->title, "node/$node->nid");
      }
    }
    $items ? $output .= theme('item_list',$items,t('Users %types',array('%type'=>flexinode_node_name($node)))) : NULL;
    $items= array();
  }
  
  return $output;
}
?>
